name: nudeny
description: Nudeny package to classify and detect nudity from an image.
version: 0.0.1
# repository: https://github.com/my_org/my_repo

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  path: ^1.8.0
  dio: ^5.1.1

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
